apiVersion: v2
version: v2.2.6
appVersion: v2.2.6
kubeVersion: '^1.14.0-0'
name: metacontroller-helm
description: Writing kubernetes controllers can be simple
home: https://metacontroller.github.io/metacontroller/
sources:
  - https://github.com/metacontroller/metacontroller
engine: gotpl
type: application
