apiVersion: v2
version: v2.0.6
appVersion: v2.0.6
kubeVersion: '^1.8.0-0'
name: metacontroller
description: Writing kubernetes controllers can be simple
home: https://metacontroller.github.io/metacontroller/
sources:
  - https://github.com/metacontroller/metacontroller
engine: gotpl
type: application
